sed -i '/example.com/d' ./email2.txt 
sed -i '/email.com/d' ./email2.txt 
sed -i '/sentry.io/d' ./email2.txt 
sed -i '/privacy/d' ./email2.txt 
sed -i '/abuse/d' ./email2.txt 
sed -i '/google.com/d' ./email2.txt 
sed -i '/apis/d' ./email2.txt 
sed -i '/.gov/d' ./email2.txt 
sed -i '/.edu/d' ./email2.txt 
sed -i '/sentry./d' ./email2.txt 
sed -i '/name.com/d' ./email2.txt 
sed -i '/domain.com/d' ./email2.txt 
sed -i '/domino.com/d' ./email2.txt 
sed -i '/buttonizer/d' ./email2.txt 
sed -i '/themepunch/d' ./email2.txt 
sed -i '/Crimestoppers/d' ./email2.txt 
sed -i '/crimestoppers-uk/d' ./email2.txt 
sed -i '/impress.press/d' ./email2.txt 
sed -i '/statcounter/d' ./email2.txt 
sed -i '/cloudflare/d' ./email2.txt 
sed -i '/t.co/d' ./email2.txt 
sed -i '/facebook/d' ./email2.txt 
sed -i '/rightmove/d' ./email2.txt 
sed -i '/snapsurveys/d' ./email2.txt 
sed -i '/police/d' ./email2.txt 
sed -i '/youtube/d' ./email2.txt 
sed -i '/youronlinechoices/d' ./email2.txt 

