sed -i '/example.com/d' ./email2.txt 
sed -i '/email.com/d' ./email2.txt 
sed -i '/sentry.io/d' ./email2.txt 
sed -i '/privacy/d' ./email2.txt 
sed -i '/abuse/d' ./email2.txt 
sed -i '/google.com/d' ./email2.txt 
sed -i '/apis/d' ./email2.txt 
sed -i '/.gov/d' ./email2.txt 
sed -i '/.edu/d' ./email2.txt 
sed -i '/sentry./d' ./email2.txt 
sed -i '/name.com/d' ./email2.txt 
sed -i '/domain.com/d' ./email2.txt 
sed -i '/domino.com/d' ./email2.txt 
sed -i '/buttonizer/d' ./email2.txt 
sed -i '/themepunch/d' ./email2.txt 
